sudo: false
language: generic

cache:
  directories:
  - $HOME/.stack

addons:
  apt:
    packages:
    - libgmp-dev
    - libsdl2-dev
    - libsdl2-image-dev
    - libsdl2-ttf-dev

before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
- wget https://www.libsdl.org/release/SDL2-2.0.5.tar.gz -O sdl2.tar.gz
- tar xzf sdl2.tar.gz
- pushd SDL2-* && ./configure && make && sudo make install && popd
- wget -q https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-2.0.14.tar.gz
- wget -q https://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.1.tar.gz
- wget -q https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-2.0.1.tar.gz
- wget -q -O SDL2_gfx-1.0.1.tar.gz https://sourceforge.net/projects/sdl2gfx/files/SDL2_gfx-1.0.1.tar.gz/download
- tar xzf SDL2_ttf-*.tar.gz
- tar xzf SDL2_image-*.tar.gz
- tar xzf SDL2_mixer-*.tar.gz
- tar xzf SDL2_gfx-*.tar.gz
- pushd SDL2_ttf-* && ./configure && make && sudo make install && popd
- pushd SDL2_image-* && ./configure && make && sudo make install && popd
- pushd SDL2_mixer-* && ./configure && make && sudo make install && popd
- pushd SDL2_gfx-* && ./autogen.sh && ./configure && make && sudo make install && popd
- stack --no-terminal --install-ghc test --only-dependencies

script:
- stack --no-terminal test
