name:                sdlight
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/myuon/sdlight#readme
license:             BSD3
author:              myuon
maintainer:          ioi.joi.koi.loi@gmail.com
copyright:           2017 myuon
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5

executables:
  sdlight:
    source-dirs:      src
    main:             Main.hs
